In [1]:
#replace all odd numbers of array with -1

In [5]:
import numpy
array1= numpy.array((1,2,3,4,5,6,7,8,9))
for idin array1:
    if (x%2==1):
    


IndentationError: expected an indented block (405255074.py, line 5)

In [8]:
import numpy 
array1= numpy.array((1,2,3,4,5,6,7,8,9))
for idx,x in np.ndenumerate(array1):
    if (x%2==1):
        array1[idx]=-1
array1

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [19]:
import numpy 
i=j=0
array2= numpy.array(((1,2,3),(4,5,6),(7,8,9)))
for x in array2:
    i=i+1
    for y in x:
        j=j+1
        if (array2[i-1][j-1] % 2==1):
            array2[i-1][j-1]=-1
array2

IndexError: index 3 is out of bounds for axis 0 with size 3

In [22]:
#Convert a 1-D array into a 2-D array with 3 'rows' 
array1= numpy.array((1,2,3,4,5,6,7,8,9))
array2=array1.reshape(3,-1)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
#3.Add 202 to all the values in given array
import numpy as np
array= np.arange(4).reshape(2,-1)
array2=np.array(())
print(array)
for x in np.nditer(array):
    array2=np.append(array2, x+202)#note
array2

[[0 1]
 [2 3]]


array([202., 203., 204., 205.])

In [54]:
#4.Generate a 1-D array of 10 random integers. Eachinteger should be a number between 30 and 40 (inclusive)


""".Find the positions of:elements in x where its value is more than its corresponding element in y, andelements in x where its valueisequals to its corresponding element in y.Start with these:x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])y = np.array([21, 7, 3, 45,10, 29, 55, 4, 37, 18])Desired output:
(array([1, 2, 4, 5, 6, 7, 8, 9]),)and(array([0]),) """

In [64]:
array1= x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
array2= y = np.array([21, 7, 3, 45,10, 29, 55, 4, 37, 18])
array1_higher=array1_equals=np.array(())
if (len(array1)>len(array2)):
    length=len(array1)
else:
    length=len(array2)
for x in range(length):
    if (array1[x]>array2[x]):
        array1_higher=np.append(array1_higher, x)
    if (array1[x]==array2[x]):
        array1_equals=np.append(array1_equals, x)
print(array1_higher,array1_equals)

[1. 2. 4. 5. 6. 7. 8. 9.] [0.]


In [75]:
array1= x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
array2= y = np.array([21, 7, 3, 45,10, 29, 55, 4, 37, 18])

if (len(array1)>len(array2)):
    length=len(array1)
else:
    length=len(array2)

for i in range(length):
    array1_higher=np.where(array1[i]>array2[i])
    array1_equals=np.where(array1[i]==array2[i])
print(array1_higher,array1_equals)

(array([0], dtype=int64),) (array([], dtype=int64),)


In [78]:
#6.Extract the first four columns of this 2-D arrayStart with this:
array= np.arange(100).reshape(5,-1)
print(array[0:5,0:4])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


In [93]:
#7.Swap two columns in a 2d numpy array
array= np.arange(100).reshape(5,-1)
print(array)
subst_array=np.array(array,ndmin=2)
for x in range(len(array)):
    subst_array[x, 0]=array[x, 0]
    array[x, 0]=array[x, 1]
    array[x, 1]=subst_array[x, 0]
array

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


array([[ 1,  0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [21, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [41, 40, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [61, 60, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [81, 80, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [94]:
#8.Create a 2D array containing random floats between 5 and 10

In [99]:
#9.Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10Desired output: [[100 110][120 130][140 150][160 170][180 190]]
print(np.arange(100,200,10).reshape(5,-1))#note the arange spelling


[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [100]:
#10.Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element,
arrayOne =numpy.array([[5,6,9],[21,18,27]])
arrayTwo =numpy.array([[15,33,24],[4,7,1]])
arraysum=arrayOne[:,:]+arrayTwo[:,:]#note we didn't use for loop instead used slicing
arraysum

array([[20, 39, 33],
       [25, 25, 28]])

In [104]:
arraysquare=arraysquare[:,:]**2
arraysquare

array([[   625,   1296,   6561],
       [194481, 104976, 531441]], dtype=int32)