In [1]:
import pandas as pd
df=pd.read_csv('headbrain.csv')
df

Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0         1          1             4512                 1530
1         1          1             3738                 1297
2         1          1             4261                 1335
3         1          1             3777                 1282
4         1          1             4177                 1590
..      ...        ...              ...                  ...
232       2          2             3214                 1110
233       2          2             3394                 1215
234       2          2             3233                 1104
235       2          2             3352                 1170
236       2          2             3391                 1120

[237 rows x 4 columns]

In [2]:
x=df['Head Size(cm^3)'].values
y=df['Brain Weight(grams)'].values

In [19]:
import numpy as np
x=np.array(range(10))
y=np.array(range(10))

In [21]:

n=len(x)
x=x.reshape(n,1)#x needs to be matrix
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [22]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,train_size=0.8)
xtrain

array([[8],
       [9],
       [6],
       [3],
       [4],
       [5],
       [1],
       [7]])

In [23]:
from sklearn.linear_model import LinearRegression
regmodel=LinearRegression()
regmodel.fit(xtrain,ytrain)

LinearRegression()

In [24]:
r2score=regmodel.score(x,y)

In [27]:
y_predicted=regmodel.predict(xtest)
y_predicted, xtest

(array([0., 2.]),
 array([[0],
        [2]]))