In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('headbrain.csv')
data

Gender  Age Range  Head Size(cm^3)  Brain Weight(grams)
0         1          1             4512                 1530
1         1          1             3738                 1297
2         1          1             4261                 1335
3         1          1             3777                 1282
4         1          1             4177                 1590
..      ...        ...              ...                  ...
232       2          2             3214                 1110
233       2          2             3394                 1215
234       2          2             3233                 1104
235       2          2             3352                 1170
236       2          2             3391                 1120

[237 rows x 4 columns]

In [3]:
x=data['Head Size(cm^3)'].values
y=data['Brain Weight(grams)'].values
#makes a numpy array with those values

In [4]:
x

array([4512, 3738, 4261, 3777, 4177, 3585, 3785, 3559, 3613, 3982, 3443,
       3993, 3640, 4208, 3832, 3876, 3497, 3466, 3095, 4424, 3878, 4046,
       3804, 3710, 4747, 4423, 4036, 4022, 3454, 4175, 3787, 3796, 4103,
       4161, 4158, 3814, 3527, 3748, 3334, 3492, 3962, 3505, 4315, 3804,
       3863, 4034, 4308, 3165, 3641, 3644, 3891, 3793, 4270, 4063, 4012,
       3458, 3890, 4166, 3935, 3669, 3866, 3393, 4442, 4253, 3727, 3329,
       3415, 3372, 4430, 4381, 4008, 3858, 4121, 4057, 3824, 3394, 3558,
       3362, 3930, 3835, 3830, 3856, 3249, 3577, 3933, 3850, 3309, 3406,
       3506, 3907, 4160, 3318, 3662, 3899, 3700, 3779, 3473, 3490, 3654,
       3478, 3495, 3834, 3876, 3661, 3618, 3648, 4032, 3399, 3916, 4430,
       3695, 3524, 3571, 3594, 3383, 3499, 3589, 3900, 4114, 3937, 3399,
       4200, 4488, 3614, 4051, 3782, 3391, 3124, 4053, 3582, 3666, 3532,
       4046, 3667, 2857, 3436, 3791, 3302, 3104, 3171, 3572, 3530, 3175,
       3438, 3903, 3899, 3401, 3267, 3451, 3090, 34

In [5]:
y

array([1530, 1297, 1335, 1282, 1590, 1300, 1400, 1255, 1355, 1375, 1340,
       1380, 1355, 1522, 1208, 1405, 1358, 1292, 1340, 1400, 1357, 1287,
       1275, 1270, 1635, 1505, 1490, 1485, 1310, 1420, 1318, 1432, 1364,
       1405, 1432, 1207, 1375, 1350, 1236, 1250, 1350, 1320, 1525, 1570,
       1340, 1422, 1506, 1215, 1311, 1300, 1224, 1350, 1335, 1390, 1400,
       1225, 1310, 1560, 1330, 1222, 1415, 1175, 1330, 1485, 1470, 1135,
       1310, 1154, 1510, 1415, 1468, 1390, 1380, 1432, 1240, 1195, 1225,
       1188, 1252, 1315, 1245, 1430, 1279, 1245, 1309, 1412, 1120, 1220,
       1280, 1440, 1370, 1192, 1230, 1346, 1290, 1165, 1240, 1132, 1242,
       1270, 1218, 1430, 1588, 1320, 1290, 1260, 1425, 1226, 1360, 1620,
       1310, 1250, 1295, 1290, 1290, 1275, 1250, 1270, 1362, 1300, 1173,
       1256, 1440, 1180, 1306, 1350, 1125, 1165, 1312, 1300, 1270, 1335,
       1450, 1310, 1027, 1235, 1260, 1165, 1080, 1127, 1270, 1252, 1200,
       1290, 1334, 1380, 1140, 1243, 1340, 1168, 13

In [6]:
n=len(x)
x=x.reshape(n,1)
x

array([[4512],
       [3738],
       [4261],
       [3777],
       [4177],
       [3585],
       [3785],
       [3559],
       [3613],
       [3982],
       [3443],
       [3993],
       [3640],
       [4208],
       [3832],
       [3876],
       [3497],
       [3466],
       [3095],
       [4424],
       [3878],
       [4046],
       [3804],
       [3710],
       [4747],
       [4423],
       [4036],
       [4022],
       [3454],
       [4175],
       [3787],
       [3796],
       [4103],
       [4161],
       [4158],
       [3814],
       [3527],
       [3748],
       [3334],
       [3492],
       [3962],
       [3505],
       [4315],
       [3804],
       [3863],
       [4034],
       [4308],
       [3165],
       [3641],
       [3644],
       [3891],
       [3793],
       [4270],
       [4063],
       [4012],
       [3458],
       [3890],
       [4166],
       [3935],
       [3669],
       [3866],
       [3393],
       [4442],
       [4253],
       [3727],
       [3329],
       [34

In [7]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,train_size=0.8)#test size too.

In [8]:
ytest

array([1250, 1240, 1260, 1215, 1522, 1297, 1240, 1180, 1090, 1210, 1240,
       1270, 1260, 1120, 1405, 1246, 1310, 1279, 1400, 1060,  955, 1218,
       1075, 1350, 1265, 1190, 1250, 1350, 1280, 1204, 1570, 1235, 1210,
       1370, 1135, 1312, 1235, 1350, 1318, 1460, 1525, 1350, 1230, 1346,
       1070, 1310, 1192, 1490], dtype=int64)

In [9]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
type(model)

sklearn.linear_model._base.LinearRegression

In [10]:
model.fit(xtrain,ytrain)#xtrain, ytrain inputted, regression line created, lowest loss fuction figured out, changed regression line tested the data and calculated attributes

LinearRegression()

In [11]:
y_predicted=model.predict(xtest)
y_predicted

array([1261.83739612, 1240.63609163, 1285.33763725, 1161.96137134,
       1428.38258324, 1308.32700357, 1248.29921374, 1171.66799267,
       1119.81419975, 1255.96233584, 1245.7448397 , 1289.93551051,
       1321.86518596, 1198.74435745, 1416.37702527, 1192.35842236,
       1235.78278096, 1183.41811324, 1320.33256154, 1175.49955373,
       1048.29172676, 1246.25571451, 1194.40192159, 1307.56069136,
       1191.08123534, 1211.26079022, 1269.50051823, 1319.56624933,
       1246.76658932, 1210.23904061, 1325.1858722 , 1178.05392776,
       1275.37557851, 1416.12158787, 1203.85310552, 1388.78978569,
       1300.40844406, 1276.90820293, 1320.84343634, 1259.7938969 ,
       1455.71438541, 1310.88137761, 1288.9137609 , 1349.45242554,
       1103.72164333, 1297.34319522, 1231.95121991, 1384.44734983])

In [12]:
r2score=model.score(x,y)
r2score

0.6386372329903708

In [13]:
#m=slope=model coefficient
m=model.coef_
m

array([0.2554374])

In [23]:
c=model.intercept_
c

336.2947413185394

In [24]:
model.predict([[123]])

array([368.24632079])

In [25]:
model.predict(xtest)

array([1243.40787547, 1217.95051947, 1487.07114003, 1266.26754208,
       1388.61871224, 1147.81290601, 1042.86625475, 1295.36166322,
       1337.18446236, 1349.13383354, 1261.33193224, 1402.12669705,
       1265.48823526, 1317.96156089, 1377.44864787, 1296.14097004,
       1350.1729093 , 1299.2581973 , 1307.83057228, 1338.48330706,
       1217.95051947, 1268.60546253, 1420.83006064, 1320.0397124 ,
       1204.96207253, 1153.26805372, 1162.61973551, 1208.59883768,
       1428.36335987, 1298.21912155, 1180.28402335, 1056.6340085 ,
       1357.96597746, 1417.1932955 , 1304.45357608, 1246.78487167,
       1292.24443596, 1317.44202302, 1188.07709151, 1115.6015576 ,
       1309.90872379, 1209.11837555, 1233.5366558 , 1474.34246203,
       1282.89275416, 1418.49214019, 1192.75293241, 1307.3110344 ])

In [60]:
df=pd.read_csv('housepricetrain.csv')
type(df)
newdf = df.filter(["TotalBsmtSF","PoolArea","LotArea","SalePrice"], axis=1)
newdf

TotalBsmtSF  PoolArea  LotArea  SalePrice
0             856         0     8450     208500
1            1262         0     9600     181500
2             920         0    11250     223500
3             756         0     9550     140000
4            1145         0    14260     250000
...           ...       ...      ...        ...
1455          953         0     7917     175000
1456         1542         0    13175     210000
1457         1152         0     9042     266500
1458         1078         0     9717     142125
1459         1256         0     9937     147500

[1460 rows x 4 columns]

In [61]:
newdf.isnull().sum()#have to change null values

TotalBsmtSF    0
PoolArea       0
LotArea        0
SalePrice      0
dtype: int64

In [62]:
x=newdf.drop('SalePrice',axis='columns')
y=newdf.SalePrice#newdf[saleprice]#only this changes in multi

In [65]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,train_size=0.8)

In [66]:
model2=LinearRegression()
model2.fit(xtrain,ytrain)

LinearRegression()

In [67]:
model2.predict(xtest)

array([223472.64238075, 175179.25291881, 193849.13880389, 180106.56285768,
       239559.39917168, 143340.60038717, 180976.91055529, 161348.97065128,
       194340.75080431, 185620.69508843, 194245.08308807, 169193.09545795,
       152221.81651568, 175033.80806994, 252313.77729601, 220294.65541028,
       289210.43198798, 180656.95921244, 160648.90110858, 220867.40506809,
       273506.22684051, 125126.90494696, 202931.4983288 , 195762.51816747,
       156786.16158141, 172218.78597261, 252835.59347383, 168512.21052106,
       167327.87945487, 144148.23214945, 136263.77234064, 131012.34309428,
       206087.02506239, 145690.44374718, 153241.30067278, 180974.37529202,
       150701.97203608, 160852.86629801, 142665.43322586, 198930.87318319,
       142929.52894123, 157466.97232878, 131086.35643004, 190211.12651305,
       178514.9675909 , 144991.25783714, 237961.25264278, 261394.13828611,
       132632.70836225, 138971.40822759, 128379.10889251, 197610.01648524,
       247618.86945862, 2