In [ ]:
!pip install opencv-contrib-python

In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np

In [2]:
img = cv2.imread('family dogs.jpeg')

In [3]:
img

array([[[ 64, 109,  76],
        [ 66, 111,  78],
        [ 68, 113,  80],
        ...,
        [ 66, 115,  65],
        [ 62, 113,  63],
        [ 61, 112,  62]],

       [[ 67, 112,  79],
        [ 67, 112,  79],
        [ 67, 112,  79],
        ...,
        [ 66, 115,  65],
        [ 64, 113,  63],
        [ 60, 111,  61]],

       [[ 68, 113,  80],
        [ 67, 112,  79],
        [ 65, 110,  77],
        ...,
        [ 66, 115,  65],
        [ 63, 112,  62],
        [ 60, 109,  59]],

       ...,

       [[  4,   2,   8],
        [  5,   3,   9],
        [  6,   4,  10],
        ...,
        [ 46,  65,  46],
        [ 43,  65,  46],
        [ 42,  67,  47]],

       [[  1,   3,   3],
        [  1,   3,   4],
        [  4,   3,   7],
        ...,
        [ 35,  51,  33],
        [ 34,  54,  35],
        [ 37,  60,  38]],

       [[  0,   1,   0],
        [  0,   1,   1],
        [  1,   0,   4],
        ...,
        [ 26,  40,  22],
        [ 27,  46,  25],
        [ 35,  56,  34]]

In [5]:
#show image
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
#save img
status=cv2.imwrite(r'saved img of family dogs2.jpg',img)

print("image written status:",status)

image written status: True


In [7]:
#convert to grey img
greyimg=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow('Gray image',greyimg)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
#edge detection using canny edge detection algorithm
imgcanny=cv2.Canny(img,150,200)
cv2.imshow('image',imgcanny)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
#cropping image
width,height= 250,350
point1=np.float32([[111,219],[287,188],[154,482],[352,440]])
point2=np.float32([[0,0],[width,0],[0,height],[width,height]])
matrix=cv2.getPerspectiveTransform(point1,point2)
cropped = cv2.warpPerspective(img,matrix,(width,height))

cv2.imshow('cropped image',cropped)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
#access image properties
print(img.shape)

#extracting the height and width of an image
h,w = img.shape[:2]
#displaying the height and width
print("height={}, width={}".format(h,w))

(1024, 1280, 3)
height=1024, width=1280


In [11]:
print(img.size)

3932160


In [12]:
img.dtype

dtype('uint8')

In [13]:
#extrating the rgb values of a pixel
(b,g,r)=img[100,100]

print("r={},b={},g={}".format(r,g,b))

r=21,b=31,g=23


In [14]:
#extracting a single color value from a pixel
r=img[100,100,1]
r

31

In [15]:
#modify pixel value
px=img[100,100]
print(px)

px=[255,255,255]
img[100,100]=px

px=img[100,100]
print(px)

[23 31 21]
[255 255 255]


In [16]:
#extracting region of interest
#by slicing the pixels of the image
roi= img[100:500, 200:500]
cv2.imshow('Gray image',roi)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
#resize is window resizing
# resize() function takes 2 parameters,
# the image and the dimensions
resize = cv2.resize(img, (800, 800))
cv2.imshow('image',resize)
cv2.waitKey(0)
cv2.destroyAllWindows()

-1

In [ ]:
image = cv2.imread('family dogs.jpeg')
y=0
x=0
h=100
w=200
crop = image[y:y+h, x:x+w]
cv2.imshow('Image', crop)
cv2.waitKey(0) 

In [24]:
img[100,100]=[255,255,255]
print(img[100,100])

[255 255 255]


In [25]:
img[100,101]

array([27, 35, 25], dtype=uint8)

In [32]:
print(type(img[100,102]))

<class 'numpy.ndarray'>


In [29]:
img[100,101]=[255,255,255]

In [30]:
img[100,101]

array([255, 255, 255], dtype=uint8)

In [36]:
newimg=cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)

In [37]:
cv2.imshow('Gray image',newimg)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [38]:
a,b,c=(1000, 850),(200, 200), (255, 0, 0)
a

(1000, 850)

In [39]:
imgGray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# threshold the image by setting all pixel values less than 225
# to 255 (white; foreground) and all pixel values >= 225 to 255
# (black; background), thereby segmenting the image
thresh = cv2.threshold(imgGray, 225, 255, cv2.THRESH_BINARY_INV)[1]
cv2.imshow("Thresh", thresh)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
# Create a VideoCapture object and read from input file
#cap = cv2.VideoCapture('')
cap = cv2.VideoCapture(0)
#cap = cv2.VideoCapture(1)

# Check if camera opened successfully
if (cap.isOpened()== False):
	print("Error opening video file")

# Read until video is completed
while(cap.isOpened()):
	
# Capture frame-by-frame
	ret, frame = cap.read()
	if ret == True:

            # Our operations on the frame come here
            # gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

	# Display the resulting frame
		cv2.imshow('Frame', frame)
		
	# Press Q on keyboard to exit
		if cv2.waitKey(1) & 0xFF == ord('q'):
			break

# Break the loop
	else:
		break
# When everything done, release the video capture object
cap.release()

# Closes all the frames
cv2.destroyAllWindows()


In [18]:
cap = cv2.VideoCapture(0)

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Our operations on the frame come here
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Display the resulting frame
    cv2.imshow('frame',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()
